### ISSUE TITLE
asdfsda

### ISSUE THREAD

**Issue by KaukinenConfed** [KaukinenConfed/JustStarting_2020#15]
dasfdsafsad

**Comment by KaukinenConfed** [comment]
what branch were you having problems on ? which function? a specific commit point?

**Comment by DKaukinen** [comment]
this makes no sense

**Comment by NotNerty** [comment]
I agree.

**Comment by KaukinenConfed** [comment]
if you feel this is an answer to your question, please close the issue.

**Comment by KaukinenConfed** [comment]
this has been taken care of last december
